### ISSUE TITLE
Price does not show up even after configuring the autosuggest popular products section with the below config

### ISSUE THREAD

**Issue by albingeorge** [unbxd/autosuggest#23]
```
"popularProducts": {
    "count": 6,
    "price": true,
    "priceFunctionOrKey": "final_price",
    "image": true,
    "imageUrlOrFunction": function(){
        return "https://new.truefacet.com/media/catalog/product/cache/1/image/155x155/9df78eab33525d08d6e5fb8d27136e95/placeholder/default/logo.png";
    },
    "currency": "USD",
    "header": "Popular Searches"
}
```

In here, the autosuggest returns the below response for popular products:

```
{
    autosuggest: "seller watch",
    doctype: "POPULAR_PRODUCTS",
    name: "seller watch",
    final_price: 110,
    price_fq: 110,
    imageUrl: [
    "https://new.truefacet.com/media/catalog/product/cache/1/image/155x155/9df78eab33525d08d6e5fb8d27136e95/placeholder/default/logo.png"
    ],
    url_path: "https://new.truefacet.com/seller-watch.html",
    uniqueId: "popularProduct_9270",
    unbxdAutosuggestScore: 0
}
```

**Comment by rahulcs** [comment]
@albingeorge is this still open?

**Comment by albingeorge** [comment]
Yes, this issue is still existing. I had done a workaround for truefacets, i.e I had to enable the "Add to cart" button and then hide the button and quantity input box from CSS.

**Comment by rahulcs** [comment]
oh, yeah but thats how it is built. I will update the readme. The price is displayed only when showCarts is set to true. 
Not actually an issue.

**Comment by rahulcs** [comment]
it seems too cumbersome to have 
`price === true && showCarts === true` to just display a price field.
lets have the library display it, when `price === true`

**Comment by albingeorge** [comment]
Yes, that would be better. In the html, I noticed that the div which shows price is inside of the dive container which contains the cart. It would be better if we could move that price div to outside of the cart container, so that when we say ```price === true``` it shows the price without showing the cart.

**Comment by floydpraveen** [comment]
Let's show price by default.
