### ISSUE TITLE
Autosuggest box moves down when header is fixed where search box is present.

### ISSUE THREAD

**Issue by AnshuHanda** [unbxd/autosuggest#24]
In int.localbanya.com , header is fixed. When user scroll down and search something in search box then autosuggest position gets weird . It moves down on the page

**Comment by rahulcs** [comment]
@AnshuHanda is this fixed? can you share a screenshot? explain it to @santosh1994

**Comment by santosh1994** [comment]
.unbxd-as-wrapper.unbxd-as-extra-right {

   1. z-index: 999999 !important;
   2. position: fixed !important;
   3. /* top: 34px !important; */

}


change the position to absolute or remove position property

**Comment by rahulcs** [comment]
cool.. @AnshuHanda if the issue is fixed with this, close it.
